export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const FORGOT_ROUTE = '/forgot'
export const GROUPS_ROUTE = '/groups'
export const EVENTS_ROUTE = '/events'
export const MESSAGES_ROUTE = '/messages'
export const SETTINGS_ROUTE = '/settings'
export const NOTIFICATIONS_ROUTE = '/notifications'
