export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
export const FORGOT_ROUTE = '/forgot'
export const DISCOVER_ROUTE = '/discover'
export const MESSAGES_ROUTE = '/messages'
export const SETTINGS_ROUTE = '/settings'
export const NOTIFICATIONS_ROUTE = '/notifications'
